### ISSUE TITLE
Does this run on a MikroTik RB951G-2HnD?

### ISSUE THREAD

**Issue by Zero3K** [ShadwDrgn/eap_proxy#2]
*subject*

**Comment by lmlsna** [comment]
No. Unless you create a metarouter instance running linux. But mikrotiks have built in functionality to nat these frames around. Just add a switch or bridge filter for 0x888E type frames.

**Comment by Zero3K** [comment]
How do I add the filter?

**Comment by lmlsna** [comment]
Not really in the scope of this project's issues... Do a google search or ask stackoverflow or send me an email.On Nov 5, 2017 4:39 PM, Zero3K <notifications@github.com> wrote:How do I add the filter?

**Comment by Zero3K** [comment]
I emailed you.

**Comment by lmlsna** [comment]
Lol k. Please close this issue.
