### ISSUE TITLE
what actualy is this?

### ISSUE THREAD

**Issue by sakgoyal** [ShadwDrgn/eap_proxy#5]
i got a link to this GitHub from a reddit mentioning that this will improve the wifi on my bgw210. how do i use this and how much better will it make my wifi?

**Comment by ShadwDrgn** [comment]
nope

**Comment by sakgoyal** [comment]
but what actually is this? what does it do?

**Comment by ShadwDrgn** [comment]
If you do not understand what this is, you will not be able to use it. I don't have the time nor the inclination to explain the technical details of EAP to random passers by on the internet.
